### ISSUE TITLE
LEGAL: Remove copyright notice from footer - DO

### ISSUE THREAD

**Issue by bradyk** [DevProgress/HillaryBNB#20]
The copyright notice isn't necessary, and it makes things confusing. Should either be removed or replaced by "HillaryBNB is licenced under the GNU Affero GPL 3+ open source license. The source is available on GitHub" or similar.

**Comment by dsjoerg** [comment]
Hi Brady, I would be happy to remove it, less stuff is better.  However I could use some more guidance on why it isn't necessary here.
Looking at http://www.nolo.com/legal-encyclopedia/when-do-you-need-copyright-notice-websites-and-where-do-you-place-it.html it seems like the main value here is to make people think twice about malicious copying such as HilaryBNB.com with one L, run by our enemies in order to confuse people, for example.

Many sites, such as hillaryclinton.com and this site github.com, put the copyright notice on every page.  So far I have found one example of a site that instead puts a copyright notice into their Legal section: http://www.ycombinator.com/legal/

To look at it another way, why not leave things as they are?  You mentioned it makes thing confusing.  What is the confusion?

**Comment by NanKrafft** [comment]
@dsjoerg @bradyk current thoughts on this? 

Unless there is reason not to I would go with leaving it on every page.

**Comment by bradyk** [comment]
wowee this is old. :)
@NanKrafft @dsjoerg 
Having a "Copyright 2016" really tells the viewer "hands off, this is mine!" when really we want to say "Heyo this is open source! woo!"

Which is why I think we should either remove it all together, or mention the OS license we're using specifically.

**Comment by dsjoerg** [comment]
I'm not going to oppose removing it altogether, since it's not going to hurt our chances of defeating Trump and it will remove one issue from the list.

**Comment by NanKrafft** [comment]
Okay. Changing issue to "remove copyright" :)
