### ISSUE TITLE
Can't login using FaceBook

### ISSUE THREAD

**Issue by seeyew** [DevProgress/HillaryBNB#21]
When I try to login using Facebook, I see a pop up that says 

App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.
<img width="1205" alt="screen shot 2016-06-30 at 4 54 55 pm" src="https://cloud.githubusercontent.com/assets/1076930/16508082/228f98a0-3ee4-11e6-88a0-98402cf46d87.png">

**Comment by dsjoerg** [comment]
@seeyew I believe I've fixed that now, could you please try again?

**Comment by seeyew** [comment]
@dsjoerg So I can login through Facebook but it also asks for google login. Is that supposed to happen?

**Comment by dsjoerg** [comment]
Not sure what you mean, can you show me a screenshot?   For me it's like this.  Before logging in: 
![image](https://cloud.githubusercontent.com/assets/783273/16511579/c335fa66-3f1f-11e6-84c8-6f40d65ab6d6.png)

After logging in via Facebook:
![image](https://cloud.githubusercontent.com/assets/783273/16511588/d49cedb4-3f1f-11e6-817c-0ba488d2c6a3.png)

**Comment by seeyew** [comment]
Here it is Step 1
<img width="831" alt="screen shot 2016-06-30 at 9 09 23 pm" src="https://cloud.githubusercontent.com/assets/1076930/16511663/69da3f30-3f07-11e6-9a4f-b32c07f85191.png">

Step 2
<img width="666" alt="screen shot 2016-06-30 at 9 09 38 pm" src="https://cloud.githubusercontent.com/assets/1076930/16511628/2d44676c-3f07-11e6-93fb-6ab1d0c8667b.png">

Then I see this
<img width="590" alt="screen shot 2016-06-30 at 9 09 48 pm" src="https://cloud.githubusercontent.com/assets/1076930/16511638/46fe579e-3f07-11e6-85f0-c92d6d0b5786.png">

**Comment by dsjoerg** [comment]
Wow that is bizarre.  There was a record for you in the database with a Google oauth token.  I wonder if your record got screwed up by the Facebook misconfiguration I had before.

I deleted that record so you'll be coming in clean.  Could you try again?

If it's still happening for you, and since it's not happening for me, I'd like to figure out a reliable way to reproduce the problem.  To start off with:
a) can you make a note of the time when you started and stopped your login activity so I can look at the logs for clues
b) can you try again in an incognito window; i wonder if old cookies are triggering a weird bug

Thank you!

**Comment by mt0321** [comment]
For what it's worth, I was just able to log in using Facebook and it worked as expected.

**Comment by dsjoerg** [comment]
great!
