### ISSUE TITLE
DESIGN: site logo - consider NEW/UPDATE

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#6]

**Comment by dsjoerg** [comment]
and if we get a new logo, then we could use a new favicon as well

**Comment by dsjoerg** [comment]
definitely need a proper site logo now that we can't use the trademark H from the campaign

**Comment by NanKrafft** [comment]
I have reached out to a graphic designer to see about a few mock ups for replacement design for the lowercase "h" - will circle back soon

**Comment by NanKrafft** [comment]
Ryan notes that top option might be too close to official campaign. 

![screen shot 2016-10-11 at 10 34 36 am](https://cloud.githubusercontent.com/assets/13854320/19281276/581fa5fe-8f9e-11e6-8599-ef06f8659f13.png)

**Comment by NanKrafft** [comment]
![screen shot 2016-10-12 at 2 42 38 pm](https://cloud.githubusercontent.com/assets/13854320/19328782/30958386-908a-11e6-9851-3bbe7f9eb7db.png)

**Comment by dsjoerg** [comment]
very cool!
fwiw i still like # 2 best, the other ones stress the BNB too much for my liking.

**Comment by NanKrafft** [comment]
![screen shot 2016-10-13 at 9 34 40 am](https://cloud.githubusercontent.com/assets/13854320/19357873/4f82ceea-9128-11e6-81fa-ff9f75166c91.png)

**Comment by dsjoerg** [comment]
still like # 2 from the original set best

**Comment by epan** [comment]
How obvious should the logo make it that it's affiliated with Hillary campaign? If this is a goal, then keeping the wordmark of Hillary as # 1 in the original does that job better.

Other than that I generally prefer the # 1 in the original post as well because the weight of the text of Hillary and BNB is not overly different as in # 2 in the original post.

If you feel that the BNB in original # 1 is too dominating, you could also ask if the designer can bump it down as it is larger than the second one or if they're open to more iteration you could present the dominance of the BNB as an issue and ask for some opinions and solutions on that.

😺

**Comment by rschroed** [comment]
Unless anyone feels strongly otherwise, why don't we go with this? It's similar, but not too close to the official brand (we need to keep a bit of distance), and seems to balance the Hillary // BnB the best. 

![hbnb](https://cloud.githubusercontent.com/assets/12657/19397887/a53460b6-91fe-11e6-9015-85db1b67276e.png)

**Comment by rschroed** [comment]
per slack, let's use the image attached above. I can provide a mock up if required, but it's probably easier to just drop the image in and we'll see how it looks.

**Comment by dsjoerg** [comment]
this is great!  we'll need a favicon too and will probably want to change both at the same time, yes?

**Comment by NanKrafft** [comment]
![screen shot 2016-10-17 at 9 03 28 am](https://cloud.githubusercontent.com/assets/13854320/19458165/4de290f2-947f-11e6-9972-2b0daca0bc99.png)

**Comment by dsjoerg** [comment]
OK!  Done in deb81de419a26bb290705538406ea716dda26737

**Comment by dsjoerg** [comment]
Thanks @rschroed !
