### ISSUE TITLE
Creating a visit or hosting for today after midnight UTC is an error

### ISSUE THREAD

**Issue by mattjacobus** [DevProgress/HillaryBNB#86]
Not likely the user will want to do this, but may get unintentionally triggered.  The start date for a host listing or a visit will be flagged as being in the past if it is past midnight in UTC, the default time zone in config/application.rb.  Not sure how to fix this.  We could send the timezone from the browser when we bring up the form, but maybe there is a most standard way.

Feel free to close if you don't think this is worth it.

**Comment by dsjoerg** [comment]
This seems worth fixing, since some people (especially organizers "testing" the system to see if they want to use it) may do this and we don't want them to see any errors.

I see three ways to fix it:
- change the server's timezone to be Eastern time
- allow start dates to be in the past
- when the user specifies a start date of yesterday, change the start date to be today

The first seems easiest unless that triggers some kind of unexpected issues.  I Googled a little for possible issues around this and didn't find anything serious.

So I vote to do the first @mattjacobus, if you say OK I'll go ahead and do it.

**Comment by mattjacobus** [comment]
I agree #1 is the easiest and makes sense, but reduces the possibility of errors rather than eliminating them.  If you're in the Western timezone there is a 3 hour window where you will get an error if you create something for today.

I vote for allowing start dates to be for no earlier than yesterday.  If you don't like that we can send the local timezone (which datepicker uses to determine "today") with the dates.

**Comment by dsjoerg** [comment]
I'm fine with allowing start dates to be for no earlier than yesterday.

An alternative to consider: the server could tell the page what is the earliest selectable day.  And we could set the server timezone to Pacific time.

**Comment by mattjacobus** [comment]
I think enforcing no earlier than yesterday on the server works fine because there is already client side checking.  The datepicker uses the local time zone (the user's) to enforce no earlier than today.  We will never get errors and we're not more permissive.

**Comment by dsjoerg** [comment]
OK! I'm sold.

**Comment by dsjoerg** [comment]
@mattjacobus are you going to do this one?

**Comment by mattjacobus** [comment]
Yes, just sent pull request.

**Comment by dsjoerg** [comment]
@mattjacobus destroyed this with https://github.com/DevProgress/HillaryBNB/pull/89
